### PR TITLE
Added TCPKISSDevice

### PR DESCRIPTION
**Pull request by hemna**
This patch adds the TCPKISSDevice.   I have been able to use
this to connect to direwolf's KISS socket and receive aprs packets.

### CODE REVIEW

**Comment by hemna** [comment]
Here is my test.py script that I used to run this

https://gist.github.com/hemna/16d55299f26d5a742b4d1b3c83852762

**Comment by hemna** [comment]
Here is an updated version that also creates a reply APRS message and sends it back out the TCPKISSDevice (which is actually direwolf)

https://gist.github.com/hemna/b0449a4e015f5f5c24032998cd3c253c

**Comment by hemna** [comment]
Here is where I am planning on using this PR

https://github.com/craigerl/aprsd/pull/50

**Comment by sjlongland** [comment]
Sounds like a great plan… I'm a bit tied up this and next weekend so it'll be a little while before I can review the code, but I do appreciate the effort.  Once the dust settles, I should get a chance to have a look.

**Comment by hemna** [comment]
any review updates for this?

**Comment by sjlongland** [comment]
Hi,

Sadly not… between work, helping a friend of ours move house and assisting with a horse endurance ride (where `aioax25` is a major player), I've been flat out.

I will try to schedule some time in to look at it, but I'm not sure exactly when that will happen.

**Comment by sjlongland** [comment]
Hi, apologies for the delays… been called away from the computer over the week-ends, and last week-end, I was in bed recovering from the last of a cold.

Long term, I think I'd like to see this using the `asyncio.Protocol` infrastructure, there may be some bits in PR #5 that could be used for both TCP and serial.  I had a work project where I had to deal with `asyncio_serial` so maybe a re-working of this and the other interface could be done.

One problem I did observe with this pull request though as it stands now: it appears in some cases, seems `assert_called_once` doesn't exist in Python 3.5 (which is standard in Debian 9), it appears this function was added in Python 3.6 and this library targets Python 3.4.

https://www.travis-ci.org/github/sjlongland/aioax25/jobs/760485038

**Comment by hemna** [comment]
I have updated the assert_called_once issue.

**Comment by sjlongland** [comment]
Many thanks for the contribution.  I can probably see things being re-worked a little to get non-blocking I/O but this is a good start.

**Pull request merged**
